server:
  address: localhost
  port: 8763

spring:
  application:
    name: DRIVELAB-CORE-SERVICE
  datasource:
    url: jdbc:h2:file:./DriveLabCore/src/main/resources/demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

eureka:
  client:
    enabled: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka