spring:
  application:
    name: ZUUL-APIGATEWAY-SERVICE

server:
  address: localhost
  port: 8762

eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: true
    securePortEnabled: true
    securePort: ${server.port}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    registerWithEureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 2

zuul:
  # ssl-hostname-validation-enabled: false
  ignored-services: "*"
  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000
    max-total-connections: 5000
    max-per-route-connections: 5
    # TODO: Add routes
#  routes:
#    ocsp-responder-service:
#      service-id: OCSP-RESPONDER-SERVICE
#      path: /api/ocsp/**
#      sslHostnameValidationEnabled: false
#      url: https://localhost:8764/
#    certificate-authority-service:
#      service-id: CERTIFICATE-AUTHORITY-SERVICE
#      path: /api/certificate-authority/**
#      sslHostnameValidationEnabled: false
#      url: https://localhost:8763/
#    siem-center-service:
#      service-id: SIEM-CENTER-SERVICE
#      path: /api/siem-center/**
#      sslHostnameValidationEnabled: false
#      url: https://localhost:8765/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 5
  MaxTotalHttpConnections: 10
  MaxConnectionsPerHost: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

keycloak:
  realm: drivelab
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: drivelab_api_gateway
  bearer-only: true
  credentials:
    secret: 96479995-5ed8-4e63-a85d-a890cfb1b417
    # TODO: Add security constraints
#  securityConstraints:
#    - authRoles: []
#      securityCollections:
#        - name: Public access
#          patterns: ['/api/ocsp/*', '/api/certificate-authority/public/*']
#    - authRoles: [defencefirst_operator]
#      securityCollections:
#        - name: Operator access
#          patterns: ['/api/siem-center/operator/*']
#    - authRoles: [defencefirst_administrator]
#      securityCollections:
#        - name: Administrator access
#          patterns: ['/api/siem-center/administrator/*', '/api/certificate-authority/private/*']
  cors: true